# Generated by Django 3.1.3 on 2020-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_shippingaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
